apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  labels:
    app: microservices-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      name: aggregator-service
      app: microservices-kubernetes
  template:
    metadata:
      name: aggregator-service
      labels:
        name: aggregator-service
        app: microservices-kubernetes

    spec:
      containers:
        - name: aggregator-service
          image: shivangiaggarwal/assignment2:aggregator_service
          ports:
            - containerPort: 8092
