apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    name: aggregator-service
    app: microservices-kubernetes

spec:
  type: LoadBalancer
  ports:
    - targetPort: 8092
      port: 8092
  selector:
    name: aggregator-service
    app: microservices-kubernetes

