apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    name: order
    app: microservices-kubernetes

spec:
  type: ClusterIP
  ports:
    - targetPort: 8091
      port: 8091
  selector:
    name: order
    app: microservices-kubernetes
