apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: microservices-kubernetes

spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    name: mysql
