apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: microservices-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      name: user
      app: microservices-kubernetes
  template:
    metadata:
      name: user
      labels:
        name: user
        app: microservices-kubernetes
    spec:
      containers:
        - name: user
          image: shivangiaggarwal/kubernetes:user
          ports:
            - containerPort: 8090
