apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
    app: microservices-kubernetes

spec:
  type: ClusterIP
  ports:
    - targetPort: 8090
      port: 8090
  selector:
    name: user
    app: microservices-kubernetes
